# Generated by Django 4.0.1 on 2022-01-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_status',
            field=models.CharField(choices=[('new', 'New'), ('in_work', 'In_work'), ('close', 'Close'), ('error', 'Error')], default='new', max_length=80),
        ),
    ]
